---

#Copyright Â© 2020, Oracle and/or its affiliates.
#The Universal Permissive License (UPL), Version 1.0

#role: db_discovery
#file: tasks/discover_tag.yml

# Get details of all compartments in tenancy
- name: Scanning compartment - "{{ compartment_ocid }}"
  oci_identity_compartment_facts:
    compartment_id: "{{ compartment_ocid }}"
    depth: 100
    fetch_subcompartments: True
  register: compartment_facts

- name: Fetch database systems with tag {{tag.namespace}}.{{tag.key}}={{tag.value}} and lifecycle_state='AVAILABLE' in scanned compartments
  oci_database_db_system_facts:
    compartment_id: "{{ item.id }}"
  loop: "{{ compartment_facts.compartments }}"
  register: all_db_system_facts
  when: item.lifecycle_state == "ACTIVE"

- name: Fetch facts for database systems with tag {{tag.namespace}}.{{tag.key}}={{tag.value}} and lifecycle_state='AVAILABLE'
  oci_database_db_system_facts:
    db_system_id: "{{ item }}"
  loop: "{{ all_db_system_facts | json_query(server_query) }}"
  vars:
#    server_query: "results[*].db_systems[?defined_tags.{{ tag.namespace}}.{{ tag.key }}=='{{ tag.value }}'].id | []"
    server_query: "results[*].db_systems[?defined_tags.{{ tag.namespace}}.{{ tag.key }}=='{{ tag.value }}' && lifecycle_state == 'AVAILABLE'].id | []"
  register: db_system_facts_tag

#- name: Print database systems with tag {{tag.namespace}}.{{tag.key}}={{tag.value}} to be patched
#  debug:
#    msg: "{{ db_system_facts_tag | json_query(server_query) }}"
#  vars:
#    server_query: "results[*].db_systems[?defined_tags.{{ tag.namespace }}.{{ tag.key }}=='{{ tag.value }}'].id | []"

- name: Set facts for database systems with {{tag.namespace}}.{{tag.key}}={{tag.value}} to be patched
  set_fact:
    db_system_id: "{{ db_system_facts_tag | json_query(server_query) }}"
  vars:
    server_query: "results[*].db_systems[?defined_tags.{{ tag.namespace }}.{{ tag.key }}=='{{ tag.value }}' && lifecycle_state == 'AVAILABLE'].id | []"

- name: Following database systems with tag {{tag.namespace}}.{{tag.key}}={{tag.value}} will be patched
  debug:
    msg: "DB Systems to be patched - {{ db_system_id }}"

- name: Exit when no database system matched with tag {{tag.namespace}}.{{tag.key}}={{tag.value}}
  meta: end_host
  when:
    db_system_id|length == 0

...
