---

#Copyright Â© 2020, Oracle and/or its affiliates.
#The Universal Permissive License (UPL), Version 1.0

#role: patch_db
#file: tasks/patchdb.yml

- name: Run APPLY for "{{ db_patch_description }}" with patch id "{{ db_patch_id }}" on database home of database {{ db_unique_name }} and db system {{ db_system_display_name }}
  oci_database_db_home:
    db_home_id: "{{ db_home_ocid }}"
    patch_details:
      patch_id: "{{ db_patch_id }}"
      action: 'APPLY'
    state: 'present'
    wait: true
    wait_timeout: 7200
  when: db_patch_id|length > 0 and db_home_patch_precheck_status
  register: db_apply_facts

- name: Print database home patch apply operation details  
  debug:
    msg: "{{ db_apply_facts }}"

- name: Check Apply Status Status for "{{ db_patch_description }}" with patch id "{{ db_patch_id }}" on database home of database {{ db_unique_name }} and db system {{ db_system_display_name }}
  oci_database_db_home_patch_history_entry_facts:
    db_home_id: "{{ db_home_ocid }}"
    patch_history_entry_id: "{{ db_apply_facts | json_query('db_home[].last_patch_history_entry_id | [0]') }}"
  register: db_home_apply_status

- name: Print apply status for "{{ db_patch_description }}" with patch id "{{ db_patch_id }}" on database home of database {{ db_unique_name }} and db system {{ db_system_display_name }}
  debug:
    msg: "Apply success status is {{ db_home_patch_apply_status }}"

- name: Fail play when apply lifecycle_state is not SUCCEEDED.
  fail:
    msg: "Failed due to database home patch apply status in {{ db_home_patch_apply_status }} state"
  when: not db_home_patch_apply_status

- name: Print apply status for "{{ db_patch_description }}" with patch id "{{ db_patch_id }}" on database home of database {{ db_unique_name }} and db system {{ db_system_display_name }}
  debug:
    msg: "Patch apply status for patch id {{ db_patch_description }} - {{ db_patch_id }} on database home of db system {{ db_system_display_name }} is {{ db_home_patch_precheck_status }} "
  when: db_home_patch_apply_status

...
